-- Phase 3: remove 91 demoted industry tags unsupported by the career's own text.
-- Compact equivalent of supabase/migrations/20260818020000_demotion_cleanup.sql
-- Purely subtractive: only secondary_industries changes; primary_industry is untouched.
-- Each row is guarded on its exact current secondary_industries, so re-running is a no-op.
-- Revert: reports/phase3_demotion_cleanup_revert.sql

begin;

update public.careers c
set secondary_industries = v.new_sec
from (values
  ('3300a681-5c81-4b1b-92b5-dd0ff5b8a611', 'Hospitality & Events,Entrepreneurship,Design & Creative', 'Entrepreneurship,Design & Creative'),  -- Baker (Specialty/Artisanal): drop Hospitality & Events
  ('65795be1-b10f-4e82-b9ef-fe4154c845f6', 'Environment & Sustainability,Science & Research,Law & Government,Tech & Engineering', 'Science & Research,Law & Government,Tech & Engineering'),  -- Environmental Graphic Designer (Interior): drop Environment & Sustainability
  ('74d913e4-cc62-49e5-a1a1-0e7a52870eb8', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Exhibition Graphic Designer: drop Science & Research
  ('3c26327b-edf2-452e-ac2b-24cf441edbec', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Science & Research', 'Business & Finance,Tech & Engineering,Science & Research'),  -- Hotel Event Manager: drop Supply Chain & Operations
  ('68dc2d2a-6f9e-4562-9657-ee648ae4c0cf', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Arts & Performance', 'Healthcare & Medicine,Tech & Engineering,Arts & Performance'),  -- Music Journalist: drop Science & Research
  ('73cef218-0324-43fc-8fe7-044ced23db3b', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Referee: drop Gaming & Esports
  ('e0ebf060-11ac-4490-89c4-2e0808329bc7', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Referee/Umpire: drop Gaming & Esports
  ('c6b5328b-3f72-46d9-9a51-0c8cecbbaf28', 'Environment & Sustainability,Business & Finance,Science & Research', 'Business & Finance,Science & Research'),  -- Regenerative Supply Chain Manager: drop Environment & Sustainability
  ('a2674345-7339-46b8-a901-8e7b42663fda', 'Social Impact & Nonprofit,Education & Coaching,Law & Government,Science & Research', 'Education & Coaching,Law & Government,Science & Research'),  -- Social Impact Journalist: drop Social Impact & Nonprofit
  ('c88cda3e-2c9b-4813-9a71-7e62ba1a46fb', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Sound Designer (Live Theater): drop Science & Research
  ('849aeb85-bb3b-474c-9e13-192063b13abc', 'Sports & Fitness,Healthcare & Medicine,Marketing & Communications,Architecture & Urban Planning', 'Healthcare & Medicine,Marketing & Communications,Architecture & Urban Planning'),  -- Sound Designer (Theater): drop Sports & Fitness
  ('566de335-26df-4561-8c19-3210af842441', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Athletic Director (High School/College): drop Gaming & Esports
  ('4f631822-995b-482c-81f1-fd9fab3c6c90', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Executive Director (Small Nonprofit): drop Gaming & Esports
  ('705f9cdd-5529-4d75-bc19-8a9f04460898', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Faith-Based Nonprofit Director: drop Gaming & Esports
  ('34bbaa14-bed7-42c1-8196-592e12c1dfb5', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Science & Research', 'Business & Finance,Tech & Engineering,Science & Research'),  -- Fashion Technical Designer: drop Supply Chain & Operations
  ('92cf011d-8405-47ea-be77-1d87169447a3', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Fitness Director: drop Gaming & Esports
  ('475d43d2-66d7-4259-9583-f0fec7ad72e6', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Industrial Illustrator: drop Science & Research
  ('5c46f7b4-e91c-4a03-b3c4-ad1d3fb53796', 'Food & Culinary,Hospitality & Events,Business & Finance,Science & Research', 'Hospitality & Events,Business & Finance,Science & Research'),  -- International Humanitarian Aid Worker: drop Food & Culinary
  ('b00fcb03-37fe-49bb-a9ff-0267e0d9a20d', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Makeup Educator: drop Gaming & Esports
  ('1586c0e9-e7f2-46ce-a2c3-e2410988d00c', 'Hospitality & Events,Food & Culinary,Marketing & Communications,Architecture & Urban Planning', 'Food & Culinary,Marketing & Communications,Architecture & Urban Planning'),  -- Makeup Effects Artist: drop Hospitality & Events
  ('12d49303-69d0-4046-8b06-9a3c61f88231', 'Education & Coaching,Social Impact & Nonprofit,Tech & Engineering,Science & Research', 'Social Impact & Nonprofit,Tech & Engineering,Science & Research'),  -- Medical Illustrator: drop Education & Coaching
  ('e9bb9b85-87cd-4706-b46a-7a9281a2353e', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Nonprofit Board Liaison: drop Gaming & Esports
  ('795c4efa-686f-4b17-a67b-d3da47578d9b', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Nonprofit Founder: drop Gaming & Esports
  ('201e900b-0092-48c5-88e3-2c56c248bbc8', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Entrepreneurship', 'Business & Finance,Tech & Engineering,Entrepreneurship'),  -- Podcast Producer & Founder: drop Supply Chain & Operations
  ('c59c9a92-47d9-44bd-bc67-9fa771298956', 'Sports & Fitness,Healthcare & Medicine,Marketing & Communications,Science & Research', 'Healthcare & Medicine,Marketing & Communications,Science & Research'),  -- Scenic Painter: drop Sports & Fitness
  ('2e23adc0-16db-4d93-bafc-ad6812af427c', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Sports Broadcast Analyst: drop Gaming & Esports
  ('09130ec2-bb45-4968-80ad-724edd6a37d9', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Theater Director: drop Science & Research
  ('8c8d566f-4285-4160-bdee-1fd85fcd4963', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Youth Athletic Director: drop Gaming & Esports
  ('057d33ed-e6ae-45a3-9ae0-74d086a29c3f', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Artistic Director: drop Science & Research
  ('797f4d31-a133-4090-925b-9f082c549c40', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Arts Grant Administrator: drop Gaming & Esports
  ('7df04d1d-1592-4e1d-93e0-8d1c72ed95fe', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Media & Journalism', 'Tech & Engineering,Marketing & Communications,Media & Journalism'),  -- Badminton Coach: drop Gaming & Esports
  ('d011e4b8-7eb3-4a1f-9814-aaaa2214042d', 'Science & Research,Healthcare & Medicine,Tech & Engineering', 'Healthcare & Medicine,Tech & Engineering'),  -- Book Editor (Trade Publishing): drop Science & Research
  ('5aa6010e-263a-4b78-a056-bde1159906b5', 'Education & Coaching,Social Impact & Nonprofit,Tech & Engineering,Science & Research', 'Social Impact & Nonprofit,Tech & Engineering,Science & Research'),  -- Compliance Officer: drop Education & Coaching
  ('c7936700-3e3e-4607-9113-8e1fcd90d735', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- CrossFit Coach: drop Gaming & Esports
  ('eb3c8236-57eb-47ee-9caf-1ff79e823f63', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Editorial Director: drop Science & Research
  ('ddc934d7-12a8-425a-bb86-5c1f63eae865', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Social Impact & Nonprofit', 'Tech & Engineering,Marketing & Communications,Social Impact & Nonprofit'),  -- Hospital Administrator: drop Gaming & Esports
  ('6cb37cca-e4a2-4826-bd97-2dc597d3020f', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Hospital Chaplain: drop Gaming & Esports
  ('7379b7a8-8fe7-4c5c-b4b6-ee8a9c09e3c1', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Live Performance Rights Manager: drop Gaming & Esports
  ('b8790739-db13-4b86-bc5c-bd9efdf7fc33', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Science & Research', 'Business & Finance,Tech & Engineering,Science & Research'),  -- Lodging Manager: drop Supply Chain & Operations
  ('2fef7a85-61a1-4525-a43c-e3ed08596aca', 'Science & Research,Healthcare & Medicine,Tech & Engineering', 'Healthcare & Medicine,Tech & Engineering'),  -- Magazine Editor-in-Chief: drop Science & Research
  ('42befc96-dbef-4ff9-acca-d8ce428fa9bc', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Marathon Coach: drop Gaming & Esports
  ('ec30490d-ad45-422e-94a6-36174fe224c9', 'Social Impact & Nonprofit,Education & Coaching,Law & Government,Science & Research', 'Education & Coaching,Law & Government,Science & Research'),  -- Media Researcher: drop Social Impact & Nonprofit
  ('8a7b8a97-d09e-4766-a214-4640b6f7df48', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Print Designer: drop Science & Research
  ('67ecd732-aed6-44f9-a90d-b0dec8512408', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Publication Designer: drop Science & Research
  ('38dd3be2-42b9-4746-a7b0-41ce36689b12', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning', 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning'),  -- Puppetry Director: drop Science & Research
  ('31155388-b1c3-425f-b2aa-39bb30739595', 'Fashion & Beauty,Design & Creative,Marketing & Communications,Healthcare & Medicine', 'Design & Creative,Marketing & Communications,Healthcare & Medicine'),  -- Spa Director: drop Fashion & Beauty
  ('65caa85a-ff60-4e50-9f02-ef4d1fda08b6', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Arts Accessibility Coordinator: drop Gaming & Esports
  ('412fc54a-9d79-4681-8721-47db747da8f4', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Science & Research', 'Business & Finance,Tech & Engineering,Science & Research'),  -- Bridal Stylist: drop Supply Chain & Operations
  ('28c669b2-396d-4618-80ff-c9f4284f989c', 'Science & Research,Healthcare & Medicine,Tech & Engineering,Marketing & Communications', 'Healthcare & Medicine,Tech & Engineering,Marketing & Communications'),  -- Broadcasting Director: drop Science & Research
  ('4fdd3728-84d4-40b8-ae8e-1d1afbff3c81', 'Fashion & Beauty,Design & Creative,Tech & Engineering', 'Design & Creative,Tech & Engineering'),  -- Color Grading Technician (Beauty Retail): drop Fashion & Beauty
  ('4134df2c-97ab-40cf-8c3c-de9d9ff4f8a7', 'Education & Coaching,Hospitality & Events,Law & Government', 'Hospitality & Events,Law & Government'),  -- Debate Tournament Director: drop Education & Coaching
  ('50e02e94-377d-426e-b983-82e3a5f6c711', 'Hospitality & Events,Design & Creative,Entrepreneurship', 'Design & Creative,Entrepreneurship'),  -- Destination Wedding Designer: drop Hospitality & Events
  ('be9bb7dd-a5b2-49db-8541-a4dd6bbebbdc', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Development Coordinator: drop Gaming & Esports
  ('9910e037-04c0-4d47-8b92-939d135cbe17', 'Gaming & Esports,Tech & Engineering,Marketing & Communications', 'Tech & Engineering,Marketing & Communications'),  -- Documentary Distributor: drop Gaming & Esports
  ('c72e4ab1-5f4d-407e-bf1b-bab5aacc74a0', 'Supply Chain & Operations,Business & Finance,Tech & Engineering', 'Business & Finance,Tech & Engineering'),  -- Eyebrow Specialist: drop Supply Chain & Operations
  ('c36b0de3-69e7-4bf2-9722-813eab8b0bbf', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Science & Research', 'Business & Finance,Tech & Engineering,Science & Research'),  -- Footwear Designer: drop Supply Chain & Operations
  ('6b3fd27c-d81a-4e17-9b8d-597033114c4f', 'Cybersecurity,Tech & Engineering,Law & Government,Science & Research', 'Tech & Engineering,Law & Government,Science & Research'),  -- Growth Hacker: drop Cybersecurity
  ('8621f068-4dd2-4265-929a-572b6b5f6406', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Law & Government', 'Tech & Engineering,Marketing & Communications,Law & Government'),  -- High School Principal: drop Gaming & Esports
  ('7e18a4bc-ec97-431a-a1d2-ea098b95216f', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Homelessness Services Coordinator: drop Gaming & Esports
  ('267ae409-c75c-40fe-b2f2-1b8e50de2c88', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Cybersecurity', 'Tech & Engineering,Marketing & Communications,Cybersecurity'),  -- Human Trafficking Prevention Coordinator: drop Gaming & Esports
  ('35ff7cda-81c9-43fb-aefc-458d9e9d50c4', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Entrepreneurship', 'Tech & Engineering,Marketing & Communications,Entrepreneurship'),  -- Incubator Program Director: drop Gaming & Esports
  ('3f230d4a-c3c5-4fc6-b8eb-95a3caafcb63', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Law & Government', 'Tech & Engineering,Marketing & Communications,Law & Government'),  -- K-12 School Principal: drop Gaming & Esports
  ('6207a784-617a-4422-a68c-f0bfaa9e3716', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Live Streaming Production Manager: drop Gaming & Esports
  ('a8037472-24c4-48b3-aefa-eb4ac4299140', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Municipal Planning Director: drop Gaming & Esports
  ('2b53168c-6cb7-47c9-a832-90e7385d70ee', 'Marketing & Communications,Business & Finance,Design & Creative,Science & Research', 'Business & Finance,Design & Creative,Science & Research'),  -- Personal Training Business Owner: drop Marketing & Communications
  ('e306a29d-e82b-4337-8bec-071433f2f513', 'Education & Coaching,Hospitality & Events,Business & Finance', 'Hospitality & Events,Business & Finance'),  -- Study Abroad Program Coordinator: drop Education & Coaching
  ('fdb0c736-63d4-4877-bf66-11c4b709072d', 'Environment & Sustainability,Science & Research,Law & Government,Tech & Engineering', 'Science & Research,Law & Government,Tech & Engineering'),  -- Sustainable Apparel Designer: drop Environment & Sustainability
  ('365887f9-96f8-4a05-a3bc-2c213dce3c78', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Volunteer Coordinator: drop Gaming & Esports
  ('cab2cacd-a9e4-4f69-9695-bb1f85a6f095', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Youth Sports Director: drop Gaming & Esports
  ('cbd89142-4422-4415-b34e-4dd45bd80ff3', 'Social Impact & Nonprofit,Education & Coaching,Law & Government', 'Education & Coaching,Law & Government'),  -- Patient Advocate: drop Social Impact & Nonprofit
  ('adf3485e-cef2-4277-92b8-9ac975e79738', 'Business & Finance,Cybersecurity,Law & Government', 'Cybersecurity,Law & Government'),  -- Financial Crime Technology Specialist: drop Business & Finance
  ('d2b40242-074e-4c8a-a770-011abd3adb34', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Media & Journalism', 'Tech & Engineering,Marketing & Communications,Media & Journalism'),  -- Golf Instructor: drop Gaming & Esports
  ('15120114-3c8b-488e-bb84-25ed57d2574b', 'Social Impact & Nonprofit,Law & Government,Education & Coaching', 'Law & Government,Education & Coaching'),  -- Healthcare Access Advocate: drop Social Impact & Nonprofit
  ('45a76936-4e3f-4080-afff-4ac3a968acb9', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Youth Development Specialist: drop Gaming & Esports
  ('47dbe29a-37c0-4a44-88fe-fa6c1742c558', 'Arts & Performance,Media & Journalism,Design & Creative,Science & Research', 'Media & Journalism,Design & Creative,Science & Research'),  -- Anesthesiologist Assistant: drop Arts & Performance
  ('5b45bc6c-f8c3-4a0d-863a-e24f7d742dda', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Elementary School Teacher: drop Gaming & Esports
  ('86e9c088-dfc4-402a-b87e-375bc49a2307', 'Cybersecurity,Tech & Engineering,Law & Government,Science & Research', 'Tech & Engineering,Law & Government,Science & Research'),  -- Forensic Nurse: drop Cybersecurity
  ('584d1946-a2b1-4819-883d-a351ae7960a9', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Social Impact & Nonprofit', 'Tech & Engineering,Marketing & Communications,Social Impact & Nonprofit'),  -- Prosecutor: drop Gaming & Esports
  ('9f740b13-c56b-4bf9-a68d-e56d0b199291', 'Marketing & Communications,Business & Finance,Design & Creative,Science & Research', 'Business & Finance,Design & Creative,Science & Research'),  -- Trademark Attorney: drop Marketing & Communications
  ('da26c81f-ab49-482b-9a3d-1eeed5eeb375', 'Sports & Fitness,Healthcare & Medicine,Marketing & Communications,Architecture & Urban Planning', 'Healthcare & Medicine,Marketing & Communications,Architecture & Urban Planning'),  -- Tutor for Learning Disabilities: drop Sports & Fitness
  ('e762e773-8edb-476a-a278-ad012c4e004e', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Recreation Therapist: drop Gaming & Esports
  ('b814a04f-88ec-4c5e-ab90-a09bbcc4741f', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Entrepreneurship', 'Tech & Engineering,Marketing & Communications,Entrepreneurship'),  -- Recreational Therapist: drop Gaming & Esports
  ('06dfa212-98be-4fa4-bcd7-3111936f6eea', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Science & Research', 'Tech & Engineering,Marketing & Communications,Science & Research'),  -- Sports Physical Therapist: drop Gaming & Esports
  ('a4f1c0ea-0397-48c8-8a9d-b67e6a78f0ac', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Media & Journalism', 'Tech & Engineering,Marketing & Communications,Media & Journalism'),  -- Chess Coach: drop Gaming & Esports
  ('87aa195e-63c0-4f54-8e62-10a0f0be46f4', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Science & Research', 'Business & Finance,Tech & Engineering,Science & Research'),  -- Genetic Testing Counselor: drop Supply Chain & Operations
  ('807c73c6-2c0d-4abb-8bdb-ed2c8748d3a0', 'Supply Chain & Operations,Business & Finance,Tech & Engineering,Science & Research', 'Business & Finance,Tech & Engineering,Science & Research'),  -- Genomic Counselor: drop Supply Chain & Operations
  ('037f4a3a-c8af-443f-84f9-28cafcff35d8', 'Fashion & Beauty,Design & Creative,Marketing & Communications,Science & Research', 'Design & Creative,Marketing & Communications,Science & Research'),  -- Literacy Coach: drop Fashion & Beauty
  ('a39b6aa4-d286-4bd7-aa51-9aaaf9daa931', 'Gaming & Esports,Tech & Engineering,Marketing & Communications,Architecture & Urban Planning', 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning'),  -- Montessori School Director: drop Gaming & Esports
  ('a21b0e51-9052-4f33-95e8-edc77f5d82f4', 'Food & Culinary,Hospitality & Events,Business & Finance,Arts & Performance', 'Hospitality & Events,Business & Finance,Arts & Performance'),  -- Nutritionist (Sports): drop Food & Culinary
  ('aac1511a-c76d-498e-aa36-8afacdb1340e', 'Tech & Engineering,Business & Finance,Design & Creative,Science & Research', 'Business & Finance,Design & Creative,Science & Research'),  -- Audiologist: drop Tech & Engineering
  ('c89fac58-78f7-4cf2-9f0f-4902eb12c582', 'Hospitality & Events,Food & Culinary,Marketing & Communications', 'Food & Culinary,Marketing & Communications')  -- Wound Care Specialist: drop Hospitality & Events
) as v(id, old_sec, new_sec)
where c.id = v.id::uuid
  and c.secondary_industries = v.old_sec;

commit;
