-- Revert the Phase 2 HIGH-confidence industry corrections.
-- Restores primary_industry and secondary_industries for the 89 rows changed by
-- supabase/migrations/20260818004500_apply_phase2_high_confidence_industry_fixes.sql
-- Values below are the pre-migration values read from the table on 2026-08-18.

begin;

update public.careers set primary_industry = 'Aviation & Transportation', secondary_industries = 'Business & Finance,Tech & Engineering' where id = '46b0fb62-8332-4c03-abf3-dfdd330b1082';  -- Aerospace Supply Chain Risk Analyst
update public.careers set primary_industry = 'Hospitality & Events', secondary_industries = 'Entrepreneurship,Design & Creative' where id = '3300a681-5c81-4b1b-92b5-dd0ff5b8a611';  -- Baker (Specialty/Artisanal)
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Business & Finance,Tech & Engineering,Architecture & Urban Planning' where id = '5ee74b3c-1521-4cad-9e06-14827a83d93d';  -- Cosmetology Salon Owner
update public.careers set primary_industry = 'Environment & Sustainability', secondary_industries = 'Science & Research,Law & Government,Tech & Engineering' where id = '65795be1-b10f-4e82-b9ef-fe4154c845f6';  -- Environmental Graphic Designer (Interior)
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = '74d913e4-cc62-49e5-a1a1-0e7a52870eb8';  -- Exhibition Graphic Designer
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering,Science & Research' where id = '3c26327b-edf2-452e-ac2b-24cf441edbec';  -- Hotel Event Manager
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Arts & Performance' where id = '68dc2d2a-6f9e-4562-9657-ee648ae4c0cf';  -- Music Journalist
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '73cef218-0324-43fc-8fe7-044ced23db3b';  -- Referee
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = 'e0ebf060-11ac-4490-89c4-2e0808329bc7';  -- Referee/Umpire
update public.careers set primary_industry = 'Environment & Sustainability', secondary_industries = 'Business & Finance,Science & Research' where id = 'c6b5328b-3f72-46d9-9a51-0c8cecbbaf28';  -- Regenerative Supply Chain Manager
update public.careers set primary_industry = 'Environment & Sustainability', secondary_industries = 'Business & Finance,Tech & Engineering' where id = '6bc29fb9-fc24-482b-b6b1-b177aa8a69e3';  -- Renewable Energy Supply Chain Manager
update public.careers set primary_industry = 'Social Impact & Nonprofit', secondary_industries = 'Education & Coaching,Law & Government,Science & Research' where id = 'a2674345-7339-46b8-a901-8e7b42663fda';  -- Social Impact Journalist
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = 'c88cda3e-2c9b-4813-9a71-7e62ba1a46fb';  -- Sound Designer (Live Theater)
update public.careers set primary_industry = 'Sports & Fitness', secondary_industries = 'Healthcare & Medicine,Marketing & Communications,Architecture & Urban Planning' where id = '849aeb85-bb3b-474c-9e13-192063b13abc';  -- Sound Designer (Theater)
update public.careers set primary_industry = 'Fashion & Beauty', secondary_industries = 'Entrepreneurship,Environment & Sustainability' where id = '3a08ce0b-0df0-496d-8f82-e95e08b341a3';  -- Sustainable Fashion Brand Strategist
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '566de335-26df-4561-8c19-3210af842441';  -- Athletic Director (High School/College)
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '4f631822-995b-482c-81f1-fd9fab3c6c90';  -- Executive Director (Small Nonprofit)
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '705f9cdd-5529-4d75-bc19-8a9f04460898';  -- Faith-Based Nonprofit Director
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering,Science & Research' where id = '34bbaa14-bed7-42c1-8196-592e12c1dfb5';  -- Fashion Technical Designer
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning' where id = '92cf011d-8405-47ea-be77-1d87169447a3';  -- Fitness Director
update public.careers set primary_industry = 'Hospitality & Events', secondary_industries = 'Environment & Sustainability,Supply Chain & Operations' where id = '3f991118-d5c9-481a-a66f-2548e745488b';  -- Hospitality Sustainability Auditor
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = '475d43d2-66d7-4259-9583-f0fec7ad72e6';  -- Industrial Illustrator
update public.careers set primary_industry = 'Food & Culinary', secondary_industries = 'Hospitality & Events,Business & Finance,Science & Research' where id = '5c46f7b4-e91c-4a03-b3c4-ad1d3fb53796';  -- International Humanitarian Aid Worker
update public.careers set primary_industry = 'Law & Government', secondary_industries = 'Science & Research,Tech & Engineering' where id = 'fc946614-8316-47be-bf30-ef5901dcedda';  -- Land Surveyor
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning' where id = 'b00fcb03-37fe-49bb-a9ff-0267e0d9a20d';  -- Makeup Educator
update public.careers set primary_industry = 'Hospitality & Events', secondary_industries = 'Food & Culinary,Marketing & Communications,Architecture & Urban Planning' where id = '1586c0e9-e7f2-46ce-a2c3-e2410988d00c';  -- Makeup Effects Artist
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Tech & Engineering,Social Impact & Nonprofit' where id = '5bdf5e87-9dcb-413a-ba5f-6508dce23ba7';  -- Marketplace Sustainability Platform Founder
update public.careers set primary_industry = 'Education & Coaching', secondary_industries = 'Social Impact & Nonprofit,Tech & Engineering,Science & Research' where id = '12d49303-69d0-4046-8b06-9a3c61f88231';  -- Medical Illustrator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = 'e9bb9b85-87cd-4706-b46a-7a9281a2353e';  -- Nonprofit Board Liaison
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '795c4efa-686f-4b17-a67b-d3da47578d9b';  -- Nonprofit Founder
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering,Entrepreneurship' where id = '201e900b-0092-48c5-88e3-2c56c248bbc8';  -- Podcast Producer & Founder
update public.careers set primary_industry = 'Sports & Fitness', secondary_industries = 'Healthcare & Medicine,Marketing & Communications,Science & Research' where id = 'c59c9a92-47d9-44bd-bc67-9fa771298956';  -- Scenic Painter
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '2e23adc0-16db-4d93-bafc-ad6812af427c';  -- Sports Broadcast Analyst
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering,Science & Research' where id = '413fac3f-52d4-4a08-aac3-de26822674cb';  -- Sustainable Fashion Designer
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = '09130ec2-bb45-4968-80ad-724edd6a37d9';  -- Theater Director
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning' where id = '8c8d566f-4285-4160-bdee-1fd85fcd4963';  -- Youth Athletic Director
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = '057d33ed-e6ae-45a3-9ae0-74d086a29c3f';  -- Artistic Director
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning' where id = '797f4d31-a133-4090-925b-9f082c549c40';  -- Arts Grant Administrator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Media & Journalism' where id = '7df04d1d-1592-4e1d-93e0-8d1c72ed95fe';  -- Badminton Coach
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering' where id = 'd011e4b8-7eb3-4a1f-9814-aaaa2214042d';  -- Book Editor (Trade Publishing)
update public.careers set primary_industry = 'Education & Coaching', secondary_industries = 'Social Impact & Nonprofit,Tech & Engineering,Science & Research' where id = '5aa6010e-263a-4b78-a056-bde1159906b5';  -- Compliance Officer
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = 'c7936700-3e3e-4607-9113-8e1fcd90d735';  -- CrossFit Coach
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = 'eb3c8236-57eb-47ee-9caf-1ff79e823f63';  -- Editorial Director
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Science & Research,Environment & Sustainability' where id = '3e06eadc-62c1-4ccf-9135-37cd4eb9fe09';  -- Food Tech Innovator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Social Impact & Nonprofit' where id = 'ddc934d7-12a8-425a-bb86-5c1f63eae865';  -- Hospital Administrator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '6cb37cca-e4a2-4826-bd97-2dc597d3020f';  -- Hospital Chaplain
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '7379b7a8-8fe7-4c5c-b4b6-ee8a9c09e3c1';  -- Live Performance Rights Manager
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering,Science & Research' where id = 'b8790739-db13-4b86-bc5c-bd9efdf7fc33';  -- Lodging Manager
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering' where id = '2fef7a85-61a1-4525-a43c-e3ed08596aca';  -- Magazine Editor-in-Chief
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '42befc96-dbef-4ff9-acca-d8ce428fa9bc';  -- Marathon Coach
update public.careers set primary_industry = 'Social Impact & Nonprofit', secondary_industries = 'Education & Coaching,Law & Government,Science & Research' where id = 'ec30490d-ad45-422e-94a6-36174fe224c9';  -- Media Researcher
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = '8a7b8a97-d09e-4766-a214-4640b6f7df48';  -- Print Designer
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = '67ecd732-aed6-44f9-a90d-b0dec8512408';  -- Publication Designer
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Business & Finance,Tech & Engineering' where id = 'fee8b398-e0f8-4673-b134-4efe6305bdf3';  -- Publishing Acquisitions Editor
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Architecture & Urban Planning' where id = '38dd3be2-42b9-4746-a7b0-41ce36689b12';  -- Puppetry Director
update public.careers set primary_industry = 'Healthcare & Medicine', secondary_industries = 'Science & Research,Tech & Engineering,Architecture & Urban Planning' where id = 'd6ec233a-e9bf-4ccf-b3ed-be474e41edfe';  -- Signage and Wayfinding Designer
update public.careers set primary_industry = 'Fashion & Beauty', secondary_industries = 'Design & Creative,Marketing & Communications,Healthcare & Medicine' where id = '31155388-b1c3-425f-b2aa-39bb30739595';  -- Spa Director
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '65caa85a-ff60-4e50-9f02-ef4d1fda08b6';  -- Arts Accessibility Coordinator
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering,Science & Research' where id = '412fc54a-9d79-4681-8721-47db747da8f4';  -- Bridal Stylist
update public.careers set primary_industry = 'Science & Research', secondary_industries = 'Healthcare & Medicine,Tech & Engineering,Marketing & Communications' where id = '28c669b2-396d-4618-80ff-c9f4284f989c';  -- Broadcasting Director
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Tech & Engineering,Environment & Sustainability' where id = '8b380c8b-4085-487f-b2ec-8b2b6dde3369';  -- Climate Fintech Founder
update public.careers set primary_industry = 'Fashion & Beauty', secondary_industries = 'Design & Creative,Tech & Engineering' where id = '4fdd3728-84d4-40b8-ae8e-1d1afbff3c81';  -- Color Grading Technician (Beauty Retail)
update public.careers set primary_industry = 'Education & Coaching', secondary_industries = 'Hospitality & Events,Law & Government' where id = '4134df2c-97ab-40cf-8c3c-de9d9ff4f8a7';  -- Debate Tournament Director
update public.careers set primary_industry = 'Hospitality & Events', secondary_industries = 'Design & Creative,Entrepreneurship' where id = '50e02e94-377d-426e-b983-82e3a5f6c711';  -- Destination Wedding Designer
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = 'be9bb7dd-a5b2-49db-8541-a4dd6bbebbdc';  -- Development Coordinator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Media & Journalism' where id = '9910e037-04c0-4d47-8b92-939d135cbe17';  -- Documentary Distributor
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering' where id = 'c72e4ab1-5f4d-407e-bf1b-bab5aacc74a0';  -- Eyebrow Specialist
update public.careers set primary_industry = 'Supply Chain & Operations', secondary_industries = 'Business & Finance,Tech & Engineering,Science & Research' where id = 'c36b0de3-69e7-4bf2-9722-813eab8b0bbf';  -- Footwear Designer
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Business & Finance' where id = 'db8733e2-91fc-40c1-927e-9b3f4ebc1f26';  -- Freight Brokerage Owner
update public.careers set primary_industry = 'Cybersecurity', secondary_industries = 'Tech & Engineering,Law & Government,Science & Research' where id = '6b3fd27c-d81a-4e17-9b8d-597033114c4f';  -- Growth Hacker
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Law & Government' where id = '8621f068-4dd2-4265-929a-572b6b5f6406';  -- High School Principal
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '7e18a4bc-ec97-431a-a1d2-ea098b95216f';  -- Homelessness Services Coordinator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Cybersecurity' where id = '267ae409-c75c-40fe-b2f2-1b8e50de2c88';  -- Human Trafficking Prevention Coordinator
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Tech & Engineering,Business & Finance' where id = '9b223863-5337-4dbf-bfa0-d9f7b11afeba';  -- Hyperlocal Delivery Service Operator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Entrepreneurship' where id = '35ff7cda-81c9-43fb-aefc-458d9e9d50c4';  -- Incubator Program Director
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Law & Government' where id = '3f230d4a-c3c5-4fc6-b8eb-95a3caafcb63';  -- K-12 School Principal
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '6207a784-617a-4422-a68c-f0bfaa9e3716';  -- Live Streaming Production Manager
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = 'a8037472-24c4-48b3-aefa-eb4ac4299140';  -- Municipal Planning Director
update public.careers set primary_industry = 'Marketing & Communications', secondary_industries = 'Business & Finance,Design & Creative,Science & Research' where id = '2b53168c-6cb7-47c9-a832-90e7385d70ee';  -- Personal Training Business Owner
update public.careers set primary_industry = 'Education & Coaching', secondary_industries = 'Hospitality & Events,Business & Finance' where id = 'e306a29d-e82b-4337-8bec-071433f2f513';  -- Study Abroad Program Coordinator
update public.careers set primary_industry = 'Environment & Sustainability', secondary_industries = 'Science & Research,Law & Government,Tech & Engineering' where id = 'fdb0c736-63d4-4877-bf66-11c4b709072d';  -- Sustainable Apparel Designer
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Science & Research' where id = '365887f9-96f8-4a05-a3bc-2c213dce3c78';  -- Volunteer Coordinator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning' where id = 'cab2cacd-a9e4-4f69-9695-bb1f85a6f095';  -- Youth Sports Director
update public.careers set primary_industry = 'Social Impact & Nonprofit', secondary_industries = 'Education & Coaching,Law & Government' where id = 'cbd89142-4422-4415-b34e-4dd45bd80ff3';  -- Patient Advocate
update public.careers set primary_industry = 'Business & Finance', secondary_industries = 'Cybersecurity,Law & Government' where id = 'adf3485e-cef2-4277-92b8-9ac975e79738';  -- Financial Crime Technology Specialist
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Media & Journalism' where id = 'd2b40242-074e-4c8a-a770-011abd3adb34';  -- Golf Instructor
update public.careers set primary_industry = 'Social Impact & Nonprofit', secondary_industries = 'Law & Government,Education & Coaching' where id = '15120114-3c8b-488e-bb84-25ed57d2574b';  -- Healthcare Access Advocate
update public.careers set primary_industry = 'Entrepreneurship', secondary_industries = 'Design & Creative,Hospitality & Events' where id = '1eb18120-dec5-414f-a207-f4a38369b765';  -- Pop-Up Shop Creator
update public.careers set primary_industry = 'Gaming & Esports', secondary_industries = 'Tech & Engineering,Marketing & Communications,Architecture & Urban Planning' where id = '45a76936-4e3f-4080-afff-4ac3a968acb9';  -- Youth Development Specialist

commit;
